# Application Settings
noisebean.version=1.5.2-beta
noisebean.prefix=!
noisebean.admin-id=123595441106452484

## SQLite
#spring.jpa.database-platform=com.scavettapps.noisebean.core.config.SQLiteDialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.EJB3NamingStrategy
#spring.jpa.hibernate.ddl-auto=none
#spring.datasource.url=jdbc:sqlite:noisebean.db
#spring.datasource.driver-class-name=org.sqlite.JDBC

## Old SQLite Settings
# spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# #spring.jpa.show-sql=true
# spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.EJB3NamingStrategy
# spring.jpa.hibernate.ddl-auto=update
# spring.datasource.initialization-mode=always
# spring.datasource.url=jdbc:sqlite:data/noisebean-sqlite.db
# spring.datasource.driver-class-name=org.sqlite.JDBC
# spring.datasource.schema=classpath:schema.sql


# Hibernate / SpringJPA configuration settings. hibernate will update the schema if it does not match
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.EJB3NamingStrategy
spring.jpa.hibernate.ddl-auto=update
spring.datasource.initialization-mode=always


# This should be overridden by the docker compose but having it here also makes it easy to debug via vscode
spring.datasource.url=jdbc:postgresql://localhost:5432/noisebean
spring.datasource.username=noisebean
spring.datasource.password=noisebean
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect